

name: CI for App automate (Python)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python-version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: 'BUILD_INFO'
          project-name: 'REPO_NAME'

      - name: Test code
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pytest -n 5 auto_app_navigation.py

